name: C/C++ CI

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    
jobs:
  build-linux:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: make
      working-directory: code
      run: make

  build-macos:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: make
      working-directory: code
      run: make

  build-windows:
  
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    - name: make
      working-directory: code
      run: nmake -f makefile.win
